### ISSUE TITLE
Cleanup Script

### ISSUE THREAD

**Issue by s3kShUn61** [JoSchaap/GoT_Wasteland_V2.Stratis#102] opened 2013-08-02 06:04 UTC
So I have disabled food and water on my server, as well as dropping of such items. The cleanup script should handle the other items however my server is experiencing heavy memory usage (approaching 1gb) with only 30 clients, with 5 fps average. The cleanup script should be better now yes? With this 'stress testing' it doesnt seem to be any different than the old cleanup script.

**Comment by JoSchaap** [comment] 2013-08-04 08:01
the old script did not work at all, and this one does, and is quite aggressive.
players only have 15 minutes to get back to their body or it will be gone

it has also been rewritten in sqf, so you can actually see how it works :)

https://github.com/JoSchaap/GoT_Wasteland_V2.Stratis/blob/master/server/WastelandServClean.sqf

**Comment by JoSchaap** [comment] 2013-08-13 14:15
dupe of #105

**Closed as completed by JoSchaap** 2013-08-13 14:15 UTC
